<a href="https://colab.research.google.com/github/RICHAR-SL/SCIKIT-Learn/blob/main/SCIKIT.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

***IMPORTAR***

In [5]:
import numpy as np

X=np.load('/content/particiones-datos-balanceados.npz')['X']
Y=np.load('/content/particiones-datos-balanceados.npz')['Y']


In [6]:
print(X.shape)
print(Y.shape)

(20, 3)
(20,)


In [12]:
from sklearn.model_selection import train_test_split

In [13]:
#Partición 60% (train) y resto(40%)
x_train, x_resto, y_train, y_resto = train_test_split(
    X,Y,test_size=0.4, random_state=123
)

#Particion "resto" en 2 mitades
x_val,x_test,y_val,y_test =train_test_split(
    x_resto,y_resto, test_size=0.5, random_state=321
)

#verificacion
print('----TAMAÑOS:---')
print('\tDataset original: ',X.shape, Y.shape)
print('\tEntrenamiento: ',x_train.shape, y_train.shape)
print('\tValidadcion: ',x_val.shape,y_val.shape)
print('\tPrueba: ', x_test.shape,y_test.shape)

print('Proporciones categorias (0/1): ')
print(f'\tDataset original: {np.sum(Y==0)/len(Y)}/{np.sum(Y==1)/len(Y)}')
print(f'\tEntrenamiento: {np.sum(y_train==0)/len(y_train)}/{np.sum(y_train==1)/len(y_train)}')
print(f'\tValidación:{np.sum(y_val==0)/len(y_val)}/{np.sum(y_val==1)/len(y_val)}')
print(f'\tPrueba: {np.sum(y_test==0)/len(y_test)}/{np.sum(y_test==1)/len(y_test)}')


----TAMAÑOS:---
	Dataset original:  (20, 3) (20,)
	Entrenamiento:  (12, 3) (12,)
	Validadcion:  (4, 3) (4,)
	Prueba:  (4, 3) (4,)
Proporciones categorias (0/1): 
	Dataset original: 0.55/0.45
	Entrenamiento: 0.5833333333333334/0.4166666666666667
	Validación:0.5/0.5
	Prueba: 0.5/0.5


datos desbalanceados


In [15]:
X=np.load('/content/particiones-datos-desbalanceados.npz')['X']
Y=np.load('/content/particiones-datos-desbalanceados.npz')['Y']
print(X)
print(Y)


[[-0.75275929  1.11852895 -7.5592353 ]
 [ 2.70428584 -3.60506139 -0.0964618 ]
 [ 1.39196365 -2.07855351 -9.31222958]
 [ 0.59195091 -1.33638157  8.18640804]
 [-2.06388816 -0.43930016 -4.82440037]
 [-2.06403288  2.85175961  3.25044569]
 [-2.65149833 -3.00326218 -3.76577848]
 [ 2.19705687  0.14234438  0.40136042]
 [ 0.60669007  0.92414569  0.93420559]
 [ 1.24843547 -4.53549587 -6.30291089]
 [-2.87649303  1.07544852  9.39169256]
 [ 2.81945911 -3.29475876  5.50265647]
 [ 1.99465584 -4.34948407  8.78997883]
 [-1.72596534  4.48885537  7.89654701]
 [-1.9090502   4.65632033  1.95799958]
 [-1.89957294  3.08397348  8.4374847 ]
 [-1.17454654 -1.95386231 -8.23014996]
 [ 0.14853859 -4.02327886 -6.08034275]
 [-0.40832989  1.84233027 -9.09545422]
 [-1.25262516 -0.59847506 -3.49339338]]
[1 0 1 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]


In [16]:

#Particion con muestreo estratificado
#Partición 60% (train) y resto(40%)
x_train, x_resto, y_train, y_resto = train_test_split(
    X,Y,test_size=0.4, random_state=20,
    stratify=Y #Muestreo esttratificado
)

#Particion "resto" en 2 mitades
x_val,x_test,y_val,y_test =train_test_split(
    x_resto,y_resto, test_size=0.5, random_state=321,
    stratify=y_resto,
)

#verificacion
print('----TAMAÑOS:---')
print('\tDataset original: ',X.shape, Y.shape)
print('\tEntrenamiento: ',x_train.shape, y_train.shape)
print('\tValidadcion: ',x_val.shape,y_val.shape)
print('\tPrueba: ', x_test.shape,y_test.shape)

print('Proporciones categorias (0s/1s): ')
print(f'\tDataset original: {np.sum(Y==0)/len(Y)}/{np.sum(Y==1)/len(Y)}')
print(f'\tEntrenamiento: {np.sum(y_train==0)/len(y_train)}/{np.sum(y_train==1)/len(y_train)}')
print(f'\tValidación:{np.sum(y_val==0)/len(y_val)}/{np.sum(y_val==1)/len(y_val)}')
print(f'\tPrueba: {np.sum(y_test==0)/len(y_test)}/{np.sum(y_test==1)/len(y_test)}')


----TAMAÑOS:---
	Dataset original:  (20, 3) (20,)
	Entrenamiento:  (12, 3) (12,)
	Validadcion:  (4, 3) (4,)
	Prueba:  (4, 3) (4,)
Proporciones categorias (0s/1s): 
	Dataset original: 0.8/0.2
	Entrenamiento: 0.8333333333333334/0.16666666666666666
	Validación:0.75/0.25
	Prueba: 0.75/0.25


In [17]:
print(f'x_train: {x_train.min(axis=0)}/{x_train.max(axis=0)}')
print(f'x_val: {x_val.min(axis=0)}/{x_val.max(axis=0)}')
print(f'xtest: {x_test.min(axis=0)}/{x_test.max(axis=0)}')





x_train: [-2.87649303 -4.34948407 -9.31222958]/[2.81945911 3.08397348 9.39169256]
x_val: [-2.65149833 -3.00326218 -9.09545422]/[2.19705687 1.84233027 0.40136042]
xtest: [-1.9090502  -4.53549587 -8.23014996]/[1.24843547 4.65632033 7.89654701]
